import fs from 'node:fs';
import path from 'node:path';
import PDFDocument from 'pdfkit'; // Assuming pdfkit is ESM compatible or has types
import Invoice from '../models/Invoice.js';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const invoiceDir = () => {
  const configuredDir = process.env.INVOICE_STORAGE_DIR || path.join('storage', 'invoices');
  const dir = path.isAbsolute(configuredDir) ? configuredDir : path.join(process.cwd(), configuredDir);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
};

const nextInvoiceNumber = async (type = 'subscription') => {
  const prefix = type === 'receipt' ? 'RCPT' : type === 'payroll' ? 'PAY' : 'INV';
  const year = new Date().getFullYear();
  const count = await Invoice.countDocuments({
    invoiceNumber: { $regex: `^${prefix}-${year}-` },
  });
  return `${prefix}-${year}-${String(count + 1).padStart(6, '0')}`;
};

const createInvoice = async ({
  academy,
  type = 'subscription',
  status = 'draft',
  lineItems,
  dueAt = null,
  paymentId = null,
  razorpayPaymentId = '',
  metadata = {},
}) => {
  const subtotal = lineItems.reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const taxAmount = 0;
  const invoice = await Invoice.create({
    academyId: academy._id,
    invoiceNumber: await nextInvoiceNumber(type),
    type,
    status,
    currency: 'INR',
    subtotal,
    taxAmount,
    total: subtotal + taxAmount,
    billingName: academy.name,
    billingEmail: academy.contactEmail,
    dueAt,
    paidAt: status === 'paid' ? new Date() : null,
    paymentId,
    razorpayPaymentId,
    lineItems,
    metadata,
  });

  return invoice;
};

const generateInvoicePdf = async (invoice) => new Promise((resolve, reject) => {
  const filePath = path.join(invoiceDir(), `${invoice.invoiceNumber}.pdf`);
  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  const stream = fs.createWriteStream(filePath);

  stream.on('finish', () => resolve(filePath));
  stream.on('error', reject);
  doc.pipe(stream);

  doc.fillColor('#0891b2').fontSize(22).text('Outplay', { continued: true });
  doc.fillColor('#0f172a').fontSize(10).text('  PlayGrid AI', { align: 'right' });
  doc.moveDown();
  doc.fontSize(18).text(invoice.type === 'receipt' ? 'Receipt' : 'Invoice');
  doc.fontSize(10).fillColor('#64748b').text(`Invoice Number: ${invoice.invoiceNumber}`);
  doc.text(`Status: ${invoice.status}`);
  doc.text(`Issued: ${new Date(invoice.createdAt).toLocaleDateString('en-IN')}`);
  if (invoice.dueAt) doc.text(`Due: ${new Date(invoice.dueAt).toLocaleDateString('en-IN')}`);
  doc.moveDown();

  doc.fillColor('#0f172a').fontSize(12).text('Bill To', { underline: true });
  doc.fontSize(11).text(invoice.billingName || 'Academy');
  if (invoice.billingEmail) doc.text(invoice.billingEmail);
  doc.text('GSTIN: To be updated');
  doc.moveDown();

  doc.fontSize(12).text('Items', { underline: true });
  invoice.lineItems.forEach((item) => {
    doc.moveDown(0.5);
    doc.fontSize(11).text(`${item.description} x ${item.quantity}`, { continued: true });
    doc.text(`Rs ${Number(item.amount).toLocaleString('en-IN')}`, { align: 'right' });
  });
  doc.moveDown();
  doc.fontSize(12).text(`Subtotal: Rs ${Number(invoice.subtotal).toLocaleString('en-IN')}`, { align: 'right' });
  doc.text(`GST: Rs ${Number(invoice.taxAmount).toLocaleString('en-IN')}`, { align: 'right' });
  doc.fontSize(15).fillColor('#0891b2').text(`Total: Rs ${Number(invoice.total).toLocaleString('en-IN')}`, { align: 'right' });
  doc.moveDown(2);
  doc.fillColor('#64748b').fontSize(9).text('This invoice is generated by Outplay. GST fields are placeholders until tax registration is configured.');
  doc.end();
});

const ensureInvoicePdf = async (invoice) => {
  if (invoice.pdfPath && fs.existsSync(invoice.pdfPath)) return invoice.pdfPath;
  const filePath = await generateInvoicePdf(invoice);
  invoice.pdfPath = filePath;
  await invoice.save();
  return filePath;
};

const formatCurrency = (amount, currency = 'INR') => {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency,
  }).format(amount);
};

const calculateTotals = (lineItems) => {
  const subtotal = lineItems.reduce((sum, item) => sum + (item.amount || 0), 0);
  const taxRate = 0; // Placeholder for GST logic
  const taxAmount = subtotal * taxRate;
  return { subtotal, taxAmount, total: subtotal + taxAmount };
};

const normalizeInvoice = (invoice) => {
  return {
    id: invoice._id,
    number: invoice.invoiceNumber,
    date: invoice.createdAt,
    period: `${new Date(invoice.createdAt).toLocaleString('default', { month: 'long' })} ${new Date(invoice.createdAt).getFullYear()}`,
    amount: formatCurrency(invoice.total),
    status: invoice.status,
    type: invoice.type,
  };
};

export {
  createInvoice,
  ensureInvoicePdf,
  normalizeInvoice,
  formatCurrency
};
